# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=io.github.slimeistdev
user=techno-sam
slug=volo-volare
modId=volare
modName=Volo Volare
modDescription=Step into a model glider and soar into a world of wonder.
authors=Slimeist
contributors=
license=EUPL 1.2 or later
# Mod Version
modVersion=0.1.0-alpha.3
# Branch Metadata
branchName=fabric-1.21.8
compatibleVersions=1.21.8
compatibleLoaders=fabric

# runtime dependency config
enable_arealib = true
